name: Continuous integration

on: push

jobs:
  ci:
    runs-on: codeberg-tiny
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # 6.2.0
        with:
          node-version: 24
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
