name: Test release current version on GitHub

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: codeberg-tiny
    timeout-minutes: 5
    steps:
      - name: Trigger Github release action
        run: |
          curl -X POST https://api.github.com/repos/hedgehog1833/obsidian-timetracker/actions/workflows/mirror-codeberg-release.yml/dispatches \
            -H "Authorization: Bearer ${{ secrets.GITHUBACTIONPAT }" \
            -H "Content-Type:application/json" \
            -d '{"ref": "main", "inputs": {"release_tag": "1.6.5"}}'
