name: Updates dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 5" # run every Friday midday

jobs:
  ci:
    runs-on: codeberg-tiny
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # 6.2.0
        with:
          node-version: 24
          cache: 'npm'
      - name: Install npm-check-update
        run: npm install -g npm-check-updates
      - name: Update dependencies in package.json
        run: ncu -u
#      - name: Install updated dependencies
#        run: npm install
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # 8.1.0

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
